### ISSUE TITLE
[Anon] Bug report: Orlock.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/necromunda-gang-war#15]
**File:** Orlock.catz

**BattleScribe version:** 2.01.17

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** The Orlocks could use an update, especially in regards to the new weapons list they got in Gang War 3

**Comment by tw6464** [comment]
Any updates on this??

**Comment by cjo197** [comment]
I'll work on the Orlock update next. Can't promise anything but hope to get it released some time over the weekend.

**Comment by tw6464** [comment]
Bump
