### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by tw6464** [BSData/necromunda-gang-war#47]
I would like to join and be able to work on this repository, as it has frustrated me to no end that it has not been updated in a very long time

**Comment by amis92** [comment]
Hello, @tw6464. Please accept the invitation in the email or on the [webpage][invitation]. Welcome aboard!

Don't forget to read through [wiki][], there are some useful guides, especially [Data Author Guide][guide].

Cheers!

[invitation]: https://github.com/BSData/necromunda-gang-war/invitations
[wiki]: https://github.com/BSData/catalogue-development/wiki
[guide]: https://github.com/BSData/catalogue-development/wiki/Data-Author-Guide

**Comment by tw6464** [comment]
@amis92 really quick, how would I work on this from the desktop app???

**Comment by amis92** [comment]
I've updated the `Quick setup` part: https://github.com/BSData/catalogue-development/wiki/Data-Author-Guide#quick-setup I hope that helps :)
