### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by Levariel** [BSData/necromunda-gang-war#51]
Howdy, I'd like to throw my hat into the ring and join this repository.

**Comment by tw6464** [comment]
@amis92 this guy wants to join up

**Comment by amis92** [comment]
Hello, @Levariel. Please accept the invitation in the email or on the [webpage][invitation]. Welcome aboard!

Don't forget to read through [wiki][], there are some useful guides, especially [Data Author Guide][guide].

Cheers!

[invitation]: https://github.com/BSData/necromunda-gang-war/invitations
[wiki]: https://github.com/BSData/catalogue-development/wiki
[guide]: https://github.com/BSData/catalogue-development/wiki/Data-Author-Guide
