### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by s-erickson** [BSData/necromunda-gang-war#57]
I have the newest compilation books and have been updating profiles and skills to match that version. I would also eventually like to create a Delaque file but I am starting with fixing up the current main file to have the latest rules.

**Comment by s-erickson** [comment]
Oh, I also have a fix for Issue #45 in my changes that are ready.

**Comment by amis92** [comment]
This issue is stale and most probably no longer useful. If you want to continue this discussion, please reopen this issue or create a new one.

Thank you.
