### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by Zan-Saar** [BSData/necromunda-gang-war#60]
I wanted to fix the battlescribe data, and update it to its latest rules.

**Comment by WindstormSCR** [comment]
Hey, please come talk to us on discord: https://discord.gg/PDaMNZ

Generally before accepting join requests we want to at least talk and see a commit via a fork and a pull request. 

The necromunda files themselves are undergoing a massive rewrite, but soon will need additional team members to help put in the rest of the gangs once the framework is complete.

**Comment by amis92** [comment]
This issue is stale and most probably no longer useful. If you want to continue this discussion, please reopen this issue or create a new one.

Thank you.
