### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by Desbane** [BSData/necromunda-gang-war#67]
I would like to join at working on getting things updated for this wonderful game. Looks like things haven't been updated in months.

**Comment by amis92** [comment]
@Desbane if you're still around, @OftKilted @WindstormSCR or @Mad-Spy were last involved. Guys?

**Comment by amis92** [comment]
This issue is stale and most probably no longer useful. If you want to continue this discussion, please reopen this issue or create a new one.

Thank you.
